apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: local-sc
  volumeName: local-pv-b
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi