apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-a
  labels:
    type: local
spec:
  storageClassName: local-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-b
  labels:
    type: local
spec:
  storageClassName: local-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
